name: state_management_test
description: Coding Test by Codigo


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/welcome/
    - assets/images/clouds/
    - assets/images/guitar/
    - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Chivo
      fonts:
        # - asset: fonts/Chivo-Black.ttf
        # - asset: fonts/Chivo-BlackItalic.ttf
        # - asset: fonts/Chivo-Bold.ttf
        # - asset: fonts/Chivo-BoldItalic.ttf
        # - asset: fonts/Chivo-Italic.ttf
        # - asset: fonts/Chivo-Light.ttf
        # - asset: fonts/Chivo-LightItalic.ttf
        - asset: assets/font/Chivo/Chivo-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
